spring:
  data:
    mongodb:
      uri:mongodb+srv://arpitachavda:0YRyFtRTyjCe6iWL@cluster0.0nu6n.mongodb.net/tweeterdb?retryWrites=true&w=majority&appName=Cluster0
      database:tweeterdb
      auto-index-creation:true

  mail:
    host: smtp.gmail.com
    port: 587
    userName: rajputarpita433@gmail.com
    password: jakb njrt arud mglw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

weather:
  api:
    key: 391b97dd3d398b9c1d8cf367a678e9ee

